#comment;
error_log_file   : /Users/ysalmi/webserv.error.log
error_log_level : warn

cluster:
  # mime_types:
  #   default_mime: text/plain
  #   html: text/html
  #   jpg: image/jpeg
  keep_alive:	65
  server_props: no
  error_page:
    file: /40x.html
    codes:
      - 401
      - 404
      - 41
  server:
    root: /Users/oelbouha/Desktop/web/pages
    Default: yes
    host: 127.0.0.1
    port: dsds 8000
    name: localhost
    # index: index.html
    error_page:
      file: /40x.html
      codes:
        - 500
        - 501
    error_page:
      file: /50x.html
      codes:
        - 41
        - 404
        - 405
    upload: /upload
    cgi:
      - .py

    route:
      uri: /test
      redirect:
        code: 301
        location: /pages
      allowed_methods:
        - POST
    
    route:
      uri: /pages
      root: /Users/oelbouha/Desktop/web/pages
      autoindex: yes
      upload: /upload
      allowed_methods:
        - POST
        - DELETE
        - GET

  server:
    host: 127.0.0.1
    index: index.html
    root: /Users/oelbouha/Desktop/web/
    port: 8004
    name: localhost\\\
    route:
      root: /Udsdsdsdsdsdsdsdsdsdsds
      uri: /
      allowed_methods:
        - GET
        - POST
