#comment;
error_log_file   : /Users/ysalmi/webserv.error.log
error_log_level : warn

cluster:
	# mime_types:
	# 	html: text/html
	# 	jpg: image/jpeg
  keep_alive:	65
  #keep_alive_timeout: 10
  server_props: no


  server:
    # host: 10.30.252.176
    port: 8000
    name: localhost
    index: index.html
    root: /Users/oelbouha/Desktop/web
    # cgi: python3 .py
    route:
      uri: /
      # index: myfile.php
      allowed_methods:
        - GET
        - POST
        - DELETE
    route:
      uri: /pages/
      # index: myfile.php
      allowed_methods:
        - GET
        - POST
  server:
    index: index.html
    root: /Users/oelbouha/Desktop/web
    port: 8004
    name: localhost\\\
    route:
      uri: /
      allowed_methods:
        - GET
        - POST
