#comment;
error_log_file   : /Users/ysalmi/webserv.error.log
error_log_level : warn

cluster:
	# mime_types:
	# 	html: text/html
	# 	jpg: image/jpeg
  keep_alive:	65
  #keep_alive_timeout: 10
  server_props: no
  error_page:
    file: /40x.html
    codes:
      - 414
      - 404
      - 414
  server:
    Default: yes
    host: 0.0.0.0
    port: 8000
    name: localhost
    index: index.html
    error_page:
      file: /40x.html
      codes:
        - 500
        - 501
    error_page:
      file: /pages/50x.html
      codes:
        - 414
        - 404
        - 405
    root: /Users/oelbouha/Desktop/web
    upload: /upload
    cgi:
      - .py
    route:
      uri: /pages
      root: /Users/oelbouha/Desktop/web/pages
      autoindex: yes
      upload: /upload
      allowed_methods:
        - POST
        - DELETE
        - GET
    route:
      uri: /test
      root: /Users/oelbouha/Desktop/web/test
      index: myfile.php
      allowed_methods:
        - DELETE
        - GET
        - POST
  server:
    # index: index.html
    root: /Users/oelbouha/Desktop/web/
    port: 8004
    name: localhost\\\
    route:
      root: /Udsdsdsdsdsdsdsdsdsdsds
      uri: /
      allowed_methods:
        - GET
        - POST
