#comment;
error_log_file   : /Users/ysalmi/webserv.error.log
error_log_level : warn

cluster:
	# mime_types:
	# 	html: text/html
	# 	jpg: image/jpeg
  # default_mime_type: text/plain
  keep_alive:	65
  #keep_alive_timeout: 10
  server_props: no
  server:
    port: 8080
    name: ysalmi.ma
    route:
      uri: /
      allowed_methods:
        - GET
        - POST
        - DELETE
  server:
    port: 8090
    name: ysalmi.ma
    route:
      uri: /
      allowed_methods:
        - GET
        - POST
