#comment;
error_log_file  : /Users/ysalmi/webserv.error.log
error_log_level : warn

cluster:
  default_mime: text/plain
  mime_types:
    jpg: image/jpeg
  keep_alive:	1
  keep_alive_timeout: 60
  server_props: no

  error_page:
    file: /40x.html
    codes:
      - 401
      - 404
      - 416
  server:
    root: /Users/oelbouha/Desktop/web/pages
    upload: /Users/oelbouha/Desktop/web/upload
    host: 0.0.0.0
    ports:
      - 8000
    names: 
      - localhost
    ports:
      - 8000
    cgi:
      - .py
      - .cpp
      - .php
    error_page:
      file: /50x.html
      codes:
        - 500
        - 501
    route:
      uri: /
      root: /Users/oelbouha/Desktop/web/pages
      autoindex: yes
      allowed_methods:
        - POST
        - DELETE
        - GET
  server:
    root: /Users/oelbouha/Desktop/web
    upload: /Users/oelbouha/Desktop/web/upload
    host: 0.0.0.0
    ports:
      - 8000
    error_page:
      file: /50x.html
      codes:
        - 500
        - 501
    error_page:
      file: /4xx.html
      codes:
        - 418
        - 404
        - 400
    cgi:
      - .h
    route:
      uri: /
      root: /Users/oelbouha/Desktop/web
      autoindex: yes
      allowed_methods:
        - POST
        - DELETE
        - GET