cluster:
  default_mime: text/plain
  mime_types:
    jpg: image/jpeg
    jpeg: image/jpeg
    mp4: video/mp4
  keep_alive:	5
  keep_alive_timeout: 60
  server_props: no

  error_page:
    file: /40x.html
    codes:
      - 401
      - 404
      - 416

  server:
    root: /Users/ysalmi/code/ws/pages
    upload: /goinfre/ysalmi
    host: 0.0.0.0
    ports:
      - 9000
    names:
      - localhost
    error_page:
      file: /50x.html
      codes:
        - 500
        - 501
    cgi:
      - .py
      - .php
    max_body_size: 0
    route:
      uri: /redir_test
      root: /Users/ysalmi/code/ws/pages
      redirect:
        code: 301
        location: /
      allowed_methods:
        - GET
        - POST
        - DELETE
    route:
      uri: /
      cgi:
        - .py
      root: /Users/ysalmi/code/ws/pages
      autoindex: yes
      index: index.html
      allowed_methods:
        - POST
        - DELETE
        - GET
    route:
      uri: /cgi tests/
      index: home.py
      root: /Users/ysalmi/code/ws/pages/cgi tests
      allowed_methods:
        - POST
        - DELETE
        - GET

  server:
    root: /Users/ysalmi/code/ws/pages
    upload: /goinfre/ysalmi
    host: 0.0.0.0
    ports:
      - 9000
    names:
      - 127.0.0.1
    error_page:
      file: /50x.html
      codes:
        - 500
        - 501
    error_page:
      file: /4xx.html
      codes:
        - 418
        - 404
        - 400
    route:
      uri: /
      root: /Users/ysalmi/code/ws/pages
      autoindex: yes
      allowed_methods:
        - POST
        - DELETE
        - GET

  # server:
  #   host: 10.30.252.176
  #   index: index.html
  #   root: /Users/ysalmi/code/w/pages
  #   upload: /Users/ysalmi/code/w/upload
  #   ports:
  #     - 8001
  #   error_page:
  #     file: /40x.html
  #     codes:
  #       - 418
  #       - 400
  #   route:
  #     uri: /
  #     allowed_methods:
  #       - GET
  #       - POST
